== Cyface Android Client

image:https://app.bitrise.io/app/c7da6c56a123928f/status.svg?token=RcVITFZtTSw7Yf5MjCQWvQ[Build
Status,link="https://app.bitrise.io/app/c7da6c56a123928f"]

This project contains the Cyface Android Client.

This app uses

* the Cyface SDK to capture sensor and location data on Android devices
* the Cyface Energy Settings to check phone settings required for location capturing in background
* the Cyface Camera Service to capture visual footage

* <<installation-guide,Installation Guide>>
* <<developer-guide,Developer Guide>>
** <<android-coding-guidelines,Android Coding Guidelines>>
** <<running-integration-tests-in-android-studio,Running integration tests in Android Studio>>
** <<importing-the-cyface-depeendencies-as-submodules,Importing the Cyface Dependencies as Submodules>>
** <<release-a-new-version,Release a new version>>
* <<license,License>>

[[installation-guide]]
== Installation Guide

To download the Cyface libraries (SDK, Energy Settings, Camera Service):

[arabic]
* You need a Github account with read-access to these Github repositories
* Create a https://github.com/settings/tokens[personal access token on Github] with "write:packages" permissions
* Create or adjust a `local.properties` file in the project root containing:
+
....
github.user=YOUR_USERNAME
github.token=YOUR_ACCESS_TOKEN
....
. Build the app `./gradlew build`

[[developer-guide]]
== Developer Guide

This section is only relevant for developers of this library.

[[android-coding-guidelines]]
=== Android Coding Guidelines

UI Elements should be represented by their own class implementing the
corresponding listener.

[[running-integration-tests-in-android-studio]]
=== Running integration tests in Android Studio

* Make sure you use the run config 'Android Instrumented Test'.

[[importing-the-cyface-depeendencies-as-submodules]]
=== Importing the Cyface Dependencies as Submodules

These libraries are downloaded as packages, see the installation guide at the top of this Readme.
If you want to include the Cyface libraries as submodules for easier development:

To get the current submodules' code run the following command:

....
$ git submodule update --init
....

If the referenced SDK version changed you can get the new code by executing:

....
$ git pull
$ git submodule update
....

If you want to select a specific submodule version you can do this by using the normal Git commands:

....
$ cd submodule/
$ git fetch -p
$ git checkout <branch_name>
....

If you want to publish the newly linked submodule version run:

....
$ git add submodule/
$ git commit
$ git push
....

[[release-a-new-version]]
=== Release a new version

Versions of this project inside the master branch are always `0.0.0`. To release a new version:

* *Make sure you use the latest Cyface libraries*, see `build.gradle`
** If you change a version also make sure you update the submodule to the same version
** The submodules are not used by the code but ease the development process
* *Create a new release branch* following the format `release/x.y`.
** `x.y` is the number of the first two sections of the new version
following http://semver.org[Semantic Versioning].
** *A Hotfix should be applied on top of the already existing
release-branch*.
*** Apply the hotfix on the `master` branch, create a Pull-Request and
pass reviewing.
*** Cherry-pick the fix on top of the already existing `release/x.y`
branch.
*** No new features are allowed on a release-branch, only fixes and
minor changes.
* *Increase version numbers* in root `build.gradle`
** `versionCode` is automatically incremented by the CI
** Set the `versionName` in the format `1.2.1`
* *Commit version bump and push branch* to Github.
** Wait until the continuous integration system passes.
** Do *not* merge the release-branch back to master.
* *Tag the new release on the release branch*.
** Ensure you are on the correct branch and commit.
** Follow the guidelines from https://keepachangelog.com["Keep a
Changelog"] in your tag description.
* *Push the release branch and tag to Github*.
** Out CI builds the Android Bundle now automatically.
** Checkout this build, copy the bundle from the artifacts and upload it to Play Store.
* *Mark the released version as 'new Release' on
https://github.com/cyface-de/android-app/releases[Github]*.



[[license]]
== License
Copyright 2017 Cyface GmbH

This file is part of the Cyface App for Android.

The Cyface App for Android is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The Cyface App for Android is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with the Cyface App for Android. If not, see http://www.gnu.org/licenses/.
