== Cyface Android Client

This project contains the Cyface Android Client.

This client app uses

* the Cyface SDK to capture data on Android devices
* the Cyface Energy Settings to check and enforce phone settings
required for capturing locations in background
* the Cyface Camera Service to capture visual footage

=== Android Coding Guidelines

UI Elements should be represented by their own class implementing the
corresponding listener.

=== Running integration tests in Android Studio

* Make sure you use the run config 'Android Instrumented Test'.

=== Importing the Cyface SDK, Cyface Android Energy Settings and Cyface Android Camera Service

These libraries are required to build this application. They are
included as Git submodules.

To get the current submodules' code run the following command:

....
$ git submodule update --init
....

If the referenced SDK version changed you can get the new code by
executing:

....
$ git pull
$ git submodule update
....

If you want to select a specific submodule version you can do this by
using the normal Git commands:

....
$ cd submodule/
$ git fetch -p
$ git checkout <branch_name>
....

If you want to publish the newly linked submodule version run:

....
$ git add submodule/
$ git commit
$ git push
....



[[license]]
== License
Copyright 2017 Cyface GmbH

This file is part of the Cyface App for Android.

The Cyface App for Android is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The Cyface App for Android is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with the Cyface App for Android. If not, see http://www.gnu.org/licenses/.
