= Cyface Android Client

image:https://app.bitrise.io/app/c7da6c56a123928f/status.svg?token=RcVITFZtTSw7Yf5MjCQWvQ[Build Status,link="https://app.bitrise.io/app/c7da6c56a123928f"]

This project contains the Cyface Android Client.

This app uses

* the Cyface SDK to capture sensor and location data on Android devices
* the Cyface Energy Settings to check phone settings required for location capturing in background
* the Cyface Camera Service to capture visual footage

== Table of Contents

* <<installation-guide,Installation Guide>>
* <<developer-guide,Developer Guide>>
** <<android-coding-guidelines,Android Coding Guidelines>>
** <<running-integration-tests-in-android-studio,Running integration tests in Android Studio>>
** <<importing-the-cyface-depeendencies-as-submodules,Importing the Cyface Dependencies as Submodules>>
** <<release-a-new-version,Release a new version>>
* <<license,License>>

[[installation-guide]]
== Installation Guide

To download the Cyface libraries (SDK, Energy Settings, Camera Service):

[arabic]
* You need a Github account with read-access to these Github repositories
* Create a https://github.com/settings/tokens[personal access token on Github] with "write:packages" permissions
* Copy `gradle.properties.template` to `gradle.properties` and adjust:
+
....
githubUser=YOUR_USERNAME
githubToken=YOUR_ACCESS_TOKEN
....
* Build the app `./gradlew build`

[[inject-secrets]]
=== Inject Secrets

The App uses a few APIs which require authentication.
The credentials are usually injected by the CI:

==== Sentry

Create a file `sentry.properties` with the following credentials,
the `auth.token` can be found on `Sentry > Settings > Account > API > Auth Tokens`.

....
defaults.project=android-app
defaults.org=cyface
auth.token=SECRET_TOKEN
....

==== Google Maps

Add the following to your `gradle.properties` file:
....
google.maps_api_key=SECRET_KEY
....

==== Cyface Guest Credentials

Add the following to your `gradle.properties` file:
....
cyface.guest_password=GUEST_PASSWORD
....


[[developer-guide]]
== Developer Guide

This section is only relevant for developers of this library.

[[android-coding-guidelines]]
=== Android Coding Guidelines

UI Elements should be represented by their own class implementing the
corresponding listener.

[[running-integration-tests-in-android-studio]]
=== Running integration tests in Android Studio

* Make sure you use the run config 'Android Instrumented Test'.

[[importing-the-cyface-depeendencies-as-submodules]]
=== Importing the Cyface Dependencies as Submodules

These libraries are downloaded as packages, see the installation guide at the top of this Readme.
If you want to include the Cyface libraries as submodules for easier development:

To get the current submodules' code run the following command:

....
$ git submodule update --init
....

If the referenced SDK version changed you can get the new code by executing:

....
$ git pull
$ git submodule update
....

If you want to select a specific submodule version you can do this by using the normal Git commands:

....
$ cd submodule/
$ git fetch -p
$ git checkout <branch_name>
....

If you want to publish the newly linked submodule version run:

....
$ git add submodule/
$ git commit
$ git push
....

[[release-a-new-version]]
=== Release a new version

See https://github.com/cyface-de/data-collector#release-a-new-version[Cyface Collector Readme]

* Increase `versionName` in root `build.gradle`, `versionCode` is automatically incremented by the CI
* Tag the release and push the branch and tag
* After pushing the release tag to Github the Bitrise CI builds the Android Bundle automatically
* Mark the release as release manually on Github, as we currently do only have Bitrise workflows
* Checkout this build, copy the `measuring-client-release-bitrise-signed.aab` bundle from the artifacts and upload it to Play Store


[[license]]
== License
Copyright 2017-2022 Cyface GmbH

This file is part of the Cyface App for Android.

The Cyface App for Android is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The Cyface App for Android is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with the Cyface App for Android. If not, see http://www.gnu.org/licenses/.
