package de.cyface.app.r4r.ui.trips

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.navArgs
import de.cyface.app.r4r.databinding.FragmentTripsDetailsBinding

class DetailsFragment : Fragment() {

    private var _binding: FragmentTripsDetailsBinding? = null

    // This property is only valid between onCreateView and onDestroyView.
    private val binding get() = _binding!!

    // For some reasons the Args class is not generated by safeargs
    //private val args: DetailsFragmentArgs by navArgs()

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentTripsDetailsBinding.inflate(inflater, container, false)
        val root: View = binding.root

        val textView: TextView = binding.tripTitle
        val measurementId = requireArguments().getLong("measurementId")
        textView.text = "measurement ${measurementId}"
        return root
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}