# This workflow ensures the building step works
#
# @author Armin Schnabel
# @version 1.0.0
# @since 2.16.0
name: Gradle Build

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GH_READ_TOKEN }}

      # Use cached dependencies unless dependencies classes or gradle files changed
          # see https://github.com/ReactiveCircus/android-emulator-runner
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Create truststore
        run: |
          # When no truststore is required by the server we create an empty file or else the build fails
          mkdir -p backend/synchronization/src/main/res/raw
          touch backend/synchronization/src/main/res/raw/truststore.jks

      - name: Create local.properties
        run: |
          # Use a personal read token to install the Cyface Utils package
          echo "github.user=${{ secrets.GH_READ_ACCOUNT }}" > local.properties
          echo "github.token=${{ secrets.GH_READ_TOKEN }}" >> local.properties

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Assemble app
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew :measuring-client:test --stacktrace

  integration:
    runs-on: macos-latest # recommended by `reactiveCircus/android-emulator-runner`
    needs: build
    strategy:
      matrix:
        api-level: [28] # API 30 not working (with step "snapshot for caching")
        arch: [x86] # x86_64 for API 30+
        target: [google_apis] # [default,google_apis] Google Maps needed in App UI test

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GH_READ_TOKEN }}

      # Use cached dependencies unless dependencies classes or gradle files changed
      # see https://github.com/ReactiveCircus/android-emulator-runner
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Create truststore
        run: |
          # When no truststore is required by the server we create an empty file or else the build fails
          mkdir -p backend/synchronization/src/main/res/raw
          touch backend/synchronization/src/main/res/raw/truststore.jks

      - name: Create local.properties
        run: |
          # Use a personal read token to install the Cyface Utils package
          echo "github.user=${{ secrets.GH_READ_ACCOUNT }}" > local.properties
          echo "github.token=${{ secrets.GH_READ_TOKEN }}" >> local.properties

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :measuring-client:connectedAndroidTest #--stacktrace

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: measuring-client/build/reports
        if: always() # also when the previous step failed
